### ISSUE TITLE
登录功能

### ISSUE THREAD

**Issue by beiklive** [beiklive/WebApp-PicBed#4]
需要一个更靠谱的登录功能

**Comment by ohto-ai** [comment]
可以试试自己写一个，你可以看下[这里](https://github.com/Ohto-Ai/webhook/blob/master/main.cpp#:~:text=if%20(!req.,%7D )

**Comment by beiklive** [comment]
登录功能需求
与后端交互后，获取token，之后所有的ajax请求都需要携带token

1. 后端添加token生成和过期验证
2. 前端封装ajax请求为统一格式

**Comment by beiklive** [comment]
已完成
