### ISSUE TITLE
图片上传方式改为直接传到cos

### ISSUE THREAD

**Issue by beiklive** [beiklive/WebApp-PicBed#6]
需要解决的问题
1. 如何不在前端暴露密钥和id实现上传

**Comment by ohto-ai** [comment]
> 需要解决的问题
> 
> 1. 如何不在前端暴露密钥和id实现上传

后段计算tmp key给前端就可以了

**Comment by ohto-ai** [comment]
这个在cos js api中有提到

**Comment by beiklive** [comment]
为了减少cos的访问频次，以及生成略缩图 ，  需要将图片发送到后端判断是否需要cos存储，暂时放弃前端直接上传。
